{{- if not .Values.shared.enabled }}
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: sso
  name: keycloak
spec:
  instances: 1
  hostname:
    hostname: keycloak.{{ .Values.domain }}
  ingress:
    enabled: true
  features:
    enabled:
      - token-exchange
      - admin-fine-grained-authz
  http:
    httpEnabled: true
  proxy:
    headers: xforwarded
{{- end }}