{{- if .Values.shared.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "pull-secret-keycloak-client-secret-openshift"
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-external-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-initial-admin
  data:
  - secretKey: password
    remoteRef:
      key: keycloak-client-secret-openshift
      property: password
  - secretKey: username
    remoteRef:
      key: keycloak-client-secret-openshift
      property: username
{{- end }}