{{- if not .Values.shared.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: "push-secret-credential-keycloak"
spec:
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - name: eso-admin-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: keycloak-initial-admin
  data:
    - match:
        secretKey: "password"
        remoteRef:
          remoteKey: credential-keycloak
          property: "password"
    - match:
        secretKey: "username"
        remoteRef:
          remoteKey: credential-keycloak
          property: "username"
{{- end }}