{{- if not .Values.shared.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret-openshift
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  CLIENT_ID: {{ .Values.openshift_client.id }}
  CLIENT_SECRET: {{ .Values.openshift_client.secret }}
{{- end }}
