apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
  name: developers
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - replicationcontrollers
  - replicationcontrollers/scale
  - replicationcontrollers/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - opentelemetry.io
  resources:
    - opentelemetrycollectors
    - instrumentations
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch

# Maybe need to be shifted over
- apiGroups:
    - image.openshift.io
  resources:
    - imagestreams
    - imagestreamimports
    - imagestreamimages
    - imagestreamtags
  verbs:
    - create
    - get
    - list
    - delete
    - update
- apiGroups:
    - build.openshift.io
  resources:
    - buildconfigs
    - builds
    - buildconfigs/instantiate
    - buildconfigs/instantiatebinary
    - builds/log
    - builds/clone
  verbs:
    - create
    - get
    - list
    - delete
    - update
# Flag for changeover
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - create
    - get
    - list
    - update
    - delete
# Flag for changeover
- apiGroups:
    - batch
  resources:
    - cronjobs
    - jobs
  verbs:
    - create
    - get
    - list
    - patch
    - update
    - delete
- apiGroups:
    - serving.knative.dev
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - services
    - revisions
    - routes
- apiGroups:
    - sources.knative.dev
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - apiserversources
- apiGroups:
    - eventing.knative.dev
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - brokers
    - triggers
- apiGroups:
    - messaging.knative.dev
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - channels
    - subscriptions
- apiGroups:
    - operators.coreos.com
  verbs:
    - get
    - list
  resources:
    - clusterserviceversions
- apiGroups:
    - operator.knative.dev
  verbs:
    - create
    - get
    - list
# SEE KEVIN
    - update
    - delete
    - patch
  resources:
    - knativeservings
    - knativeeventings
- apiGroups:
    - operator.serverless.openshift.io
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - knativekafkas
- apiGroups:
    - kafka.strimzi.io
  resources:
    - kafkanodepools
    - kafkaconnects
    - kafkabridges
    - kafkatopics
    - kafkausers
    - kafkaconnectors
    - kafkamirrormaker2s
    - kafkarebalances
    - kafkas
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
- apiGroups:
    - monitoring.coreos.com
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - patch
  resources:
    - servicemonitors
- apiGroups:
    - ''
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
    - roles
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - triggers.tekton.dev
  resources:
    - eventlisteners
    - triggerbinding
    - triggerbinding/status
    - triggers
    - triggerbindings
    - clustertriggerbindings
    - triggertemplates
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups:
    - tekton.dev
  resources:
    - pipelines
    - pipelineruns
    - tasks
    - taskruns
    - pipelineloops
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete

