# https://www.npmjs.com/package/@backstage-community/plugin-rbac-backend
## Example multiple conditionals
apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-conditional-policies
data:
  policies.yaml: |
    # Workshop admins can view templates with spec.type=workshop or service
    result: CONDITIONAL
    roleEntityRef: role:default/workshop-admins
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
    conditions:
      anyOf:
        - rule: HAS_SPEC
          resourceType: catalog-entity
          params:
            key: type
            value: service
        - rule: HAS_SPEC
          resourceType: catalog-entity
          params:
            key: type
            value: workshop
    ---
    # Developers can view most entities, and templates with spec.type=service (inferring we shouldn't view templates with spec.type=workshop)
    result: CONDITIONAL
    roleEntityRef: role:default/developers
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
    conditions:
      anyOf:
        - rule: HAS_SPEC
          resourceType: catalog-entity
          params:
            key: type
            value: service
        - rule: IS_ENTITY_KIND
          resourceType: catalog-entity
          params:
            kinds:
              - API
              - Component
              - Group
              - Location
              - Package
              - Plugin
              - Resource
              - System
              - User
    # ---
    # result: CONDITIONAL
    # roleEntityRef: role:default/workshop-admins
    # pluginId: catalog
    # resourceType: catalog-entity
    # permissionMapping:
    #   - read
    # conditions:
    #   anyOf:
    #     - rule: HAS_SPEC
    #       resourceType: catalog-entity
    #       params:
    #         key: type
    #         value: service
    #     - rule: HAS_SPEC
    #       resourceType: catalog-entity
    #       params:
    #         key: type
    #         value: workshop
