kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-plugin
data:
  kubernetes-plugin.yaml: |
    kubernetes:
      clusterLocatorMethods:
        - type: config
          clusters:
            {{- if .Values.clusters }}
            {{- range .Values.clusters  }}
            # Keycloak is not a supported OIDC provider for Kubernetes plugin
            # https://github.com/backstage/backstage/issues/19836
            # - authProvider: oidc
            #   name: {{ .name }}
            #   skipTLSVerify: true
            #   oidcTokenProvider: oidc
            #   url: https://api.{{ (eq .type "hcp") | ternary (.domain | replace "rosa." "" ) .domain }}:{{ .api_port }}
            - authProvider: serviceAccount
              customResources:
              - apiVersion: v1alpha1
                group: argoproj.io
                plural: rollouts
              - apiVersion: v1
                group: route.openshift.io
                plural: routes
              - apiVersion: v1
                group: tekton.dev
                plural: pipelineruns
              - apiVersion: v1
                group: tekton.dev
                plural: taskruns
              name: {{ .name }}
              serviceAccountToken: ${token}
              skipTLSVerify: true
              url: https://api.{{ (eq .type "hcp") | ternary (.domain | replace "rosa." "" ) .domain }}:{{ .api_port }}
            {{- end }}
            {{- else }}
            []
            {{- end }}
      serviceLocatorMethod:
        type: multiTenant

    dynamicPlugins:
      frontend:
        backstage.plugin-kubernetes:
          mountPoints:
            - mountPoint: entity.page.kubernetes/cards
              importName: EntityKubernetesContent
              config:
                layout:
                  gridColumn: "1 / -1"
                if:
                  anyOf:
                    - hasAnnotation: backstage.io/kubernetes-id
                    - hasAnnotation: backstage.io/kubernetes-namespace
