apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pull-secret-keycloak-client-secret-openshift
spec:
  refreshInterval: "2m"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-client-secret-openshift
  data:
  - secretKey: KEYCLOAK_ADMIN_PASSWORD
    remoteRef:
      key: keycloak-client-secret-openshift
      property: ADMIN_PASSWORD
  - secretKey: KEYCLOAK_ADMIN_USERNAME
    remoteRef:
      key: keycloak-client-secret-openshift
      property: ADMIN_USERNAME